language: shell

os:
  - linux
env:
  global:
    - WITH_METIS=1 THGSP_PLT=0
  jobs:
    - TORCH_VERSION=1.6.0 TORCHVISION_VERSION=0.7.0 PYTHON_VERSION=3.6 IDX=cpu
    - TORCH_VERSION=1.7.0 TORCHVISION_VERSION=0.8.1 PYTHON_VERSION=3.7 IDX=cpu

install:
  - source scripts/gcc.sh
  - source scripts/conda.sh
  - source scripts/scikit-sparse.sh
  - source scripts/metis.sh
  - conda create --yes -n test python="${PYTHON_VERSION}"
  - source activate test
  - conda install pytorch==${TORCH_VERSION} torchvision==${TORCHVISION_VERSION} cpuonly -c pytorch --yes
  - pip install --user scikit-sparse
  - pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install torch-sparse
  - pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install -U ray
  - pip install scipy
  - pip install networkx
  - pip install matplotlib
  - pip install pytest
  - pip install flake8 codecov
  - pip install pytest-cov
  - pip install -e .
script:
  - pytest
  - cd docs && pip install -r requirements.txt && make html && cd ..
after_success:
  - codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: ./docs/
  on:
      branch: main
      condition: $PYTHON_VERSION = 3.7
notifications:
  email: false