name: Doc


on:
  push:
    branches: [ main ]
  pull_request:


jobs:

  thgsp-doc:
    runs-on: ${{ matrix.os}}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.11 ]
        torch-version: [ 2.5.0 ]
        tv-version: [ 0.20.0 ]
        cuda-version: [ 'cpu' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyTorch ${{ matrix.torch-version }}+${{ matrix.cuda-version }}
        run: |
          pip install torch==${{ matrix.torch-version }} --extra-index-url https://download.pytorch.org/whl/${{ matrix.cuda-version }}
          python -c "import torch; print('PyTorch:', torch.__version__)"
          python -c "import torch; print('CUDA:', torch.version.cuda)"

      - name: Install torch-scatter, sparse, and cluster
        run: |
          pip install torch-scatter torch-sparse torch-cluster  -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+${{ matrix.cuda-version }}.html


      - name: Install main package for CPU
        run: |
          FORCE_ONLY_CPU=1 python setup.py develop
        shell:
          bash

      - name: Build Docs
        run: cd docs && pip install -r requirements.txt && make html && cd ..

      - name: Deploy Docs 🚀
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # The branch the action should deploy to.
          publish_dir: ./docs # The folder the action should deploy.
          enable_jekyll: true

