name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Building Wheels", "Linting", "Testing", "Doc" ]
    branches: [ main ]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release and Upload Wheel
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/*.whl"