name: Release

on:
  workflow_run:
    workflows: [ "Building Wheels", "Linting", "Testing" ]
    branches: [ main ]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2
      - name: Update the website of wheels
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: ${{secrets.SCRIPT}}


