name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      max-parallel: 20 # max for free user
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]
        os: [ ubuntu-20.04, ubuntu-18.04, ubuntu-16.04 ]

    runs-on: ${{ matrix.os }}
    env:
      TORCH_VERSION: 1.8.0
      TORCHVISION_VERSION: 0.9.0
      IDX: cpu
      WITH_METIS: 1
      THGSP_PLT: 0
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@master
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,spyder-ide,pytorch,nvidia
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true

      - name: System Dependencies
        shell: bash -l {0}
        run: |
          sh scripts/ga-gcc.sh
          sudo apt-get install libsuitesparse-dev

      - name: Python Dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install --upgrade pip setuptools wheel
          conda install pytorch==${TORCH_VERSION} torchvision==${TORCHVISION_VERSION} cpuonly -c pytorch --yes
          pip install --user scikit-sparse
          pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
          pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
          pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
          pip install -U ray
          pip install scipy
          pip install networkx
          pip install matplotlib

      - name: Test Dependencies
        shell: bash -l {0}
        run: |
          python -c "import torch; print(torch.__version__)"
          pip install pytest
          pip install pytest-cov

      - name: Install and Test with Pytest
        shell: bash -l {0}
        run: |
          pip install -e .
          pytest --cov=./thgsp/

      - name: Build Docs
        shell: bash -l {0}
        run: cd docs && pip install -r requirements.txt && make html && cd ..

