name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        python-version: [ 3.8 ]
        os: [ ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}
    env:
      TORCH_VERSION: 1.8.1
      TORCHVISION_VERSION: 0.9.1
      IDX: cpu
      WITH_METIS: 1
      THGSP_PLT: 0
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@master
      - name: Install System Dependencies
        run: |
          sh scripts/gcc.sh
          sh scripts/scikit-sparse.sh
          sh scripts/metis.sh

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,spyder-ide,pytorch,nvidia
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true

      - name: Install Python Dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          conda install pytorch==${TORCH_VERSION} torchvision==${TORCHVISION_VERSION} cpuonly -c pytorch --yes
          pip install --user scikit-sparse
          pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
          pip install torch-sparse
          pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
          pip install -U ray
          pip install scipy
          pip install networkx
          pip install matplotlib
          pip install pytest
          pip install flake8
          pip install pytest-cov
          pip install -e .

      - name: Install Test Dependencies
        shell: bash -l {0}
        run: |
          python -c "import torch; print(torch.__version__)"
          pip install pytest
          pip install pytest-cov

      - name: Install and Test with Pytest
        shell: bash -l {0}
        run: |
          pip install -e .
          pytest --cov=./thgsp/

      - name: Codecov via Bash
        shell: bash -l {0}
        run: bash <(curl -s https://codecov.io/bash)

      - name: Build Docs
        shell: bash -l {0}
        run: cd docs && pip install -r requirements.txt && make html && cd ..

      - name: Deploy Docs 🚀
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # The branch the action should deploy to.
          publish_dir: ./docs # The folder the action should deploy.
          enable_jekyll: true


